### PR TITLE
Use Nano server iis image

### PR DESCRIPTION
**Pull request by sridmad**
## Purpose
Reduce the size of Windows container image
* ...

## Does this introduce a breaking change?

```
[ ] Yes
[ X] No
```

## Pull Request Type
Changes to use Nano server iis image for the sample

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[X] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

### CODE REVIEW

**Comment by VipulM-MSFT** [comment]
What is sac 2016?

**Comment by sridmad** [comment]
Let me take a look and get back.

**Comment by sridmad** [comment]
Updated to use iis:nanoserver. Compressed Image size is 450MB vs 3GB for Windows Server Core

**Comment by sridmad** [comment]
Wrong branch. Creating one for 2018-09-01-preview branch

**Pull request closed without merging**
